services:
  postgres:
    image: postgres
    environment: 
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5435:5432
    volumes:
      - /var/lib/postresql/data
  mongodb:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27020:27017
    volumes:
      - /data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672